"""Package portable frozen modules and record their exact compatibility hashes."""

import argparse
import ast
import hashlib
import json
from pathlib import Path
import shutil


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def definitions(path, names):
    source = path.read_text()
    nodes = {n.name: n for n in ast.parse(source).body if isinstance(n, (ast.ClassDef, ast.FunctionDef))}
    return "\n\n\n".join(ast.get_source_segment(source, nodes[n]) for n in names)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--typing-root', type=Path, required=True)
    parser.add_argument('--run', type=Path, default=Path('runs/facial_typing_fusion_gallery_v1'))
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    destination = root/'src/exports'
    run = args.run.resolve()
    protocol = json.loads((run/'protocol.json').read_text())
    freeze = json.loads((run/'freeze.json').read_text())
    assert digest(run/'protocol.json') == freeze['protocol_sha256']
    assert digest(run/'selection.json') == freeze['selection_sha256']
    fusion_weights = run/'models/gallery.pt'
    assert digest(fusion_weights) == freeze['models']['gallery']
    typing_weights = args.typing_root/'paper_typenet/weights/typenet_68k_m50_g10_64x512_best_weights.pt'
    assert digest(typing_weights) == protocol['typing_data']['encoder_sha256']
    typing_source = args.typing_root/'paper_typenet/nn.py'
    names = ['events_to_features', 'KerasStyleLSTM', 'masked_batch_norm', 'TypeNetEncoder']
    preamble = '''"""Frozen runtime definitions copied from the registered TypeNet implementation.
Generated by scripts/export_gallery_modules.py; no training or data loading code.
"""
from __future__ import annotations
from typing import Sequence
import numpy as np
import torch
from torch import Tensor, nn
import torch.nn.functional as F

PAPER_FEATURE_COUNT = 5
PAPER_EMBEDDING_DIM = 128

'''
    (destination/'_typenet.py').write_text(preamble+definitions(typing_source, names)+'\n')
    sources = [('fusion.py', ['FusionNetwork', 'FusionClassifier']),
               ('fusion_gallery.py', ['GalleryFusionNetwork', 'GalleryFusionClassifier'])]
    fusion_preamble = '''"""Frozen inference definitions from the gallery training source snapshot.
Generated by scripts/export_gallery_modules.py.
"""
import hashlib
from pathlib import Path
import numpy as np
import torch
from torch import nn
from .facial import FEATURES

GALLERY_SIZE = 10

'''
    code = []
    for name, definitions_to_copy in sources:
        source = run/'source'/name
        assert digest(source) == protocol['source_code_sha256'][name]
        code.append(definitions(source, definitions_to_copy))
    (destination/'_fusion.py').write_text(fusion_preamble+'\n\n\n'.join(code)+'\n')
    (destination/'weights').mkdir(exist_ok=True)
    shutil.copyfile(typing_weights, destination/'weights/typenet.pt')
    shutil.copyfile(fusion_weights, destination/'weights/fusion_gallery.pt')
    metrics = json.loads((run/'metrics.json').read_text())
    upstream = json.loads((run/'pipeline_manifest.json').read_text())
    manifest = {
        'format_version': 1, 'release': 'gallery_v1', 'status': 'experimental; not promoted over the two-token model',
        'modules': {
            'typenet': {'entrypoint': 'exports.typenet.FrozenTypeNet', 'checkpoint': 'weights/typenet.pt',
                        'checkpoint_sha256': digest(typing_weights), 'source_sha256': digest(typing_source),
                        'input': {'sequence': ['N', 50, 5], 'lengths': ['N']}, 'output': ['N', 128],
                        'parameters': 200458, 'frozen': True},
            'facial': {'entrypoint': 'exports.facial.summarize', 'checkpoint': None,
                       'version': 'openface-static_mediapipe478_v1',
                       'input': {'measurements': ['usable_frames', 14], 'au_presence': ['usable_frames', 7]},
                       'output': [42], 'features': upstream['face']['features'],
                       'source_sha256': digest(root/'src/mcifacenet/facial_signals.py'),
                       'training_extractor_parity': 'unverified',
                       'video_or_image_input': False},
            'fusion': {'entrypoint': 'exports.fusion.FrozenFusion', 'checkpoint': 'weights/fusion_gallery.pt',
                       'checkpoint_sha256': digest(fusion_weights), 'input': {'face': ['N', 42], 'typing': ['N', 10, 128]},
                       'output': ['N', 2], 'classes': ['control', 'impaired'], 'threshold': .5,
                       'models': 3, 'parameters_per_model': metrics['parameters_per_network'],
                       'typing_encoder_sha256': digest(typing_weights),
                       'normalization': 'Included; submit unstandardized embeddings and summaries',
                       'frozen': True},
        },
        'training_run': run.name, 'training_protocol_sha256': digest(run/'protocol.json'),
        'participant_metrics': {role: {name: report['participant'] for name, report in rows.items()}
                                for role, rows in metrics['reports'].items()},
        'limitations': protocol['limitations'], 'tested_versions': protocol['versions'],
    }
    manifest['files_sha256'] = {str(p.relative_to(destination)): digest(p) for p in sorted(destination.rglob('*'))
                              if p.is_file() and '__pycache__' not in p.parts and p.name != 'manifest.json'}
    (destination/'manifest.json').write_text(json.dumps(manifest, indent=2, allow_nan=False)+'\n')
    print(json.dumps({'destination': str(destination), 'fusion_bytes': fusion_weights.stat().st_size,
                      'typenet_bytes': typing_weights.stat().st_size}))


if __name__ == '__main__':
    main()
