"""Frozen runtime definitions copied from the registered TypeNet implementation.
Generated by scripts/export_gallery_modules.py; no training or data loading code.
"""
from __future__ import annotations
from typing import Sequence
import numpy as np
import torch
from torch import Tensor, nn
import torch.nn.functional as F

PAPER_FEATURE_COUNT = 5
PAPER_EMBEDDING_DIM = 128

def events_to_features(
    events: Sequence[tuple[int, int, int, int]],
    sequence_length: int,
) -> tuple[np.ndarray, int]:
    """Convert (press, release, keycode, keystroke_id) events to TypeNet input.

    Timing features are computed before truncation, so the M-th retained key can
    use the following event when one exists.  The final event has no successor,
    therefore IL/PL/RL are set to zero while its HL and keycode are retained.
    Negative IL values caused by key rollover are intentionally preserved.
    """

    ordered = sorted(events, key=lambda event: (event[0], event[3]))
    count = len(ordered)
    output = np.zeros((sequence_length, PAPER_FEATURE_COUNT), dtype=np.float32)
    if count == 0:
        return output, 0

    press = np.fromiter((event[0] for event in ordered), dtype=np.float64)
    release = np.fromiter((event[1] for event in ordered), dtype=np.float64)
    keycode = np.fromiter((event[2] for event in ordered), dtype=np.float64)

    raw = np.zeros((count, PAPER_FEATURE_COUNT), dtype=np.float64)
    raw[:, 0] = (release - press) / 1_000.0  # Hold latency (HL)
    if count > 1:
        raw[:-1, 1] = (press[1:] - release[:-1]) / 1_000.0  # Inter-key (IL)
        raw[:-1, 2] = (press[1:] - press[:-1]) / 1_000.0  # Press (PL)
        raw[:-1, 3] = (release[1:] - release[:-1]) / 1_000.0  # Release (RL)
    raw[:, 4] = keycode / 255.0

    retained = min(count, sequence_length)
    output[:retained] = raw[:retained].astype(np.float32)
    return output, retained


class KerasStyleLSTM(nn.Module):
    """An LSTM with Keras-style variational recurrent dropout.

    PyTorch's built-in LSTM does not implement recurrent dropout.  This module
    uses one recurrent dropout mask per gate, held fixed across time, matching
    the behavior used by the paper's Keras/TensorFlow implementation.
    """

    def __init__(self, input_size: int, hidden_size: int, recurrent_dropout: float) -> None:
        super().__init__()
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.recurrent_dropout = recurrent_dropout
        self.kernel = nn.Parameter(torch.empty(input_size, 4 * hidden_size))
        self.recurrent_kernel = nn.Parameter(
            torch.empty(hidden_size, 4 * hidden_size)
        )
        self.bias = nn.Parameter(torch.empty(4 * hidden_size))
        self.reset_parameters()

    def reset_parameters(self) -> None:
        nn.init.xavier_uniform_(self.kernel)
        nn.init.orthogonal_(self.recurrent_kernel)
        nn.init.zeros_(self.bias)
        # Keras LSTM defaults to unit_forget_bias=True.
        with torch.no_grad():
            self.bias[self.hidden_size : 2 * self.hidden_size].fill_(1.0)

    def forward(self, inputs: Tensor, lengths: Tensor) -> tuple[Tensor, Tensor]:
        batch_size, timesteps, _ = inputs.shape
        hidden = inputs.new_zeros((batch_size, self.hidden_size))
        cell = inputs.new_zeros((batch_size, self.hidden_size))

        if self.training and self.recurrent_dropout > 0:
            recurrent_masks = [
                F.dropout(
                    torch.ones_like(hidden),
                    p=self.recurrent_dropout,
                    training=True,
                )
                for _ in range(4)
            ]
        else:
            recurrent_masks = [torch.ones_like(hidden) for _ in range(4)]

        recurrent_chunks = self.recurrent_kernel.chunk(4, dim=1)
        outputs: list[Tensor] = []
        for timestep in range(timesteps):
            projected = inputs[:, timestep] @ self.kernel + self.bias
            input_gate, forget_gate, candidate, output_gate = projected.chunk(4, dim=1)
            input_gate = input_gate + (hidden * recurrent_masks[0]) @ recurrent_chunks[0]
            forget_gate = (
                forget_gate + (hidden * recurrent_masks[1]) @ recurrent_chunks[1]
            )
            candidate = candidate + (hidden * recurrent_masks[2]) @ recurrent_chunks[2]
            output_gate = (
                output_gate + (hidden * recurrent_masks[3]) @ recurrent_chunks[3]
            )

            input_gate = torch.sigmoid(input_gate)
            forget_gate = torch.sigmoid(forget_gate)
            candidate = torch.tanh(candidate)
            output_gate = torch.sigmoid(output_gate)
            next_cell = forget_gate * cell + input_gate * candidate
            next_hidden = output_gate * torch.tanh(next_cell)

            active = (lengths > timestep).unsqueeze(1)
            cell = torch.where(active, next_cell, cell)
            hidden = torch.where(active, next_hidden, hidden)
            outputs.append(torch.where(active, hidden, torch.zeros_like(hidden)))

        return torch.stack(outputs, dim=1), hidden


def masked_batch_norm(inputs: Tensor, lengths: Tensor, layer: nn.BatchNorm1d) -> Tensor:
    """Apply feature-wise batch norm without including zero padding in stats."""

    timesteps = inputs.shape[1]
    valid_mask = (
        torch.arange(timesteps, device=inputs.device).unsqueeze(0)
        < lengths.unsqueeze(1)
    )
    valid_values = inputs[valid_mask]
    if valid_values.numel() == 0:
        raise ValueError("A batch contained no valid timesteps")

    # BatchNorm cannot estimate variance from one value. This only affects
    # pathological one-key, one-sample training batches.
    if layer.training and valid_values.shape[0] == 1:
        normalized = F.batch_norm(
            valid_values,
            layer.running_mean,
            layer.running_var,
            layer.weight,
            layer.bias,
            training=False,
            momentum=0.0,
            eps=layer.eps,
        )
    else:
        normalized = layer(valid_values)

    output = torch.zeros_like(inputs)
    output[valid_mask] = normalized
    return output


class TypeNetEncoder(nn.Module):
    """The complete 200,458-parameter TypeNet encoder from Figure 2."""

    def __init__(
        self,
        input_size: int = PAPER_FEATURE_COUNT,
        hidden_size: int = PAPER_EMBEDDING_DIM,
        dropout: float = 0.5,
        recurrent_dropout: float = 0.2,
    ) -> None:
        super().__init__()
        self.input_batch_norm = nn.BatchNorm1d(input_size)
        self.first_lstm = KerasStyleLSTM(
            input_size, hidden_size, recurrent_dropout=recurrent_dropout
        )
        self.dropout = nn.Dropout(dropout)
        self.hidden_batch_norm = nn.BatchNorm1d(hidden_size)
        self.second_lstm = KerasStyleLSTM(
            hidden_size, hidden_size, recurrent_dropout=recurrent_dropout
        )

    def forward(self, inputs: Tensor, lengths: Tensor) -> Tensor:
        if inputs.ndim != 3 or inputs.shape[-1] != PAPER_FEATURE_COUNT:
            raise ValueError(
                f"Expected [batch, time, {PAPER_FEATURE_COUNT}], got {tuple(inputs.shape)}"
            )
        lengths = lengths.clamp(min=1, max=inputs.shape[1])
        normalized_inputs = masked_batch_norm(
            inputs, lengths, self.input_batch_norm
        )
        sequence, _ = self.first_lstm(normalized_inputs, lengths)
        sequence = self.dropout(sequence)
        sequence = masked_batch_norm(
            sequence, lengths, self.hidden_batch_norm
        )
        _, embedding = self.second_lstm(sequence, lengths)
        return embedding
